In [7]:
using Random, LinearAlgebra
n = 8
magic_number = n*(n^2+1) ÷ 2
population_size = 200
nr_epochs = 20000

20000

In [8]:
using LinearAlgebra
function fitness(M)
    MSE = 0
    for i in 1:n
        MSE += abs(magic_number - sum(M[i, :])) + abs(magic_number - sum(M[:, i]))
    end
    MSE += abs(magic_number - sum(Diagonal(M))) + abs(magic_number - sum(Diagonal(reverse(M, dims=2))))
end

fitness (generic function with 1 method)

In [9]:
function mutate(parent, number_of_mutations)
    new_parent = copy(parent)
    for i in 1:number_of_mutations
        rnd = rand(1:n, 2, 2)
        temp = new_parent[rnd[1,1], rnd[1,2]]
        new_parent[rnd[1,1], rnd[1,2]] = new_parent[rnd[2,1], rnd[2,2]]
        new_parent[rnd[2,1], rnd[2,2]] = temp
    end
    return new_parent
end

mutate (generic function with 1 method)

In [10]:
function crossover(first_parent, second_parent)
    flattened_fp = hcat(first_parent'...)
    flattened_sp = hcat(second_parent'...)
    first_child = copy(flattened_fp)
    second_child = copy(flattened_sp)

    for i in rand(1:n):n*n
        if flattened_sp[i] in first_child[1:i-1]
            for k in 1:i
                if flattened_sp[k] ∉ first_child[1:i-1]
                    first_child[i] = flattened_sp[k]
                end
            end
        else
            first_child[i] = flattened_sp[i]
        end
        
        if flattened_fp[i] in second_child[1:i-1]
            for k in 1:i
                if flattened_fp[k] ∉ second_child[1:i-1]
                    second_child[i] = flattened_fp[k]
                end
            end
        else
            second_child[i] = flattened_fp[i]
        end
    end

    matrix_fc = zeros(Int32,n,n)
    matrix_sc = zeros(Int32,n,n)
    for i in 1:n
        for j in 1:n
            matrix_fc[i,j] = first_child[((i-1)*n) + j]
            matrix_sc[i,j] = second_child[((i-1)*n) + j]
        end
    end
    return matrix_fc, matrix_sc
end

crossover (generic function with 1 method)

In [11]:
function go!(initial)
    population = []
    for j in 1:population_size
        push!(population, mutate(initial, 100))
    end
    for i in 1:1000
        errors = fitness.(population)
        population = sort(population, by = x -> fitness(x))
        if fitness(population[1]) == 0 
            display(population[1])
            display(i)
            return population[1]
        end

        new_childs = []
        for j in 1:2:(population_size ÷ 2)
            childs = crossover(population[j], population[j+1])
            push!(new_childs, childs[1])
            push!(new_childs, childs[2])
        end
        population = append!(population[1:(population_size ÷ 2)], new_childs)

        for k in 1:(population_size ÷ 2)
            rnd = rand(2 : population_size)
            population[rnd] = mutate(population[rnd], fitness(population[rnd]))
        end
    end
    population = sort(population, by = x -> fitness(x))
    display(fitness.(population))
    display(population)
    return population[1]
end

go! (generic function with 1 method)

In [12]:
X = zeros(Int32, n, n)
for i in 1:n
    for j in 1:n
        X[i,j] = ((i - 1) * n) + j
    end
end
X = shuffle(X)
display(X)

Solution = go!(X)
display(Solution)
display(fitness(Solution))

4×4 Matrix{Int32}:
  4  15  13   6
 11   5   2  16
  9   8   7  10
  1  14  12   3

200-element Vector{Int64}:
 14
 14
 14
 14
 14
 14
 14
 14
 14
 14
 14
 14
 14
  ⋮
 78
 81
 82
 83
 83
 84
 85
 85
 91
 92
 96
 99

200-element Vector{Any}:
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 Int32[7 13 2 11; 9 3 14 12; 10 1 16 5; 8 15 4 6]
 ⋮
 Int32[15 13 12 1; 14 9 10 2; 4 5 3 6; 8 16 11 7]
 Int32[11 7 10 9; 6 4 5 14; 2 3 16 15; 8 1 12 13]
 Int32[11 16 13 14; 5 8 1 15; 3 7 6 10; 9 12 4 2]
 Int32[11 9 14 16; 13 3 4 12; 10 2 7 6; 15 8 1 5]
 Int32[7 14 13 15; 10 9 12 4; 5 16 2 1; 8 3 11 6]
 Int32[15 11 13 7; 3 8 2 9; 14 10 16 5; 4 1 6 12]
 Int32[8 13 2 11; 6 12

4×4 Matrix{Int32}:
  7  13   2  11
  9   3  14  12
 10   1  16   5
  8  15   4   6

14