In [51]:
using Random, LinearAlgebra
nr_epochs = 10000
nr_childs = 100

100

In [52]:
function fitness(M, n)
    magic_number = n*(n^2+1) ÷ 2
    MSE = 0
    for i in 1:n
        MSE += abs(magic_number - sum(M[i, :])) + abs(magic_number - sum(M[:, i]))
    end
    return MSE + abs(magic_number -sum(Diagonal(M))) + abs(magic_number - sum(Diagonal(reverse(M, dims=2))))
end

fitness (generic function with 1 method)

In [53]:
function mutate(parent, number_of_mutations, n)
    new_parent = copy(parent)
    for i in 1:number_of_mutations
        rnd = rand(1:n, 2, 2)
        if n != 3
            while (rnd[1,1] <= 3 && rnd[1,2] <= 3) || (rnd[2,1] <= 3 && rnd[2,2] <= 3)
                rnd = rand(1:n, 2, 2)
            end
        end
        temp = new_parent[rnd[1,1], rnd[1,2]]
        new_parent[rnd[1,1], rnd[1,2]] = new_parent[rnd[2,1], rnd[2,2]]
        new_parent[rnd[2,1], rnd[2,2]] = temp
    end
    return new_parent
end

mutate (generic function with 1 method)

In [54]:
function go!(M, n)
    for i in 1:nr_epochs
        Xs = []
        for j in 1:nr_childs
            push!(Xs, mutate(M, rand(1:n), n))
        end
        push!(Xs, M)
        errors = fitness.(Xs, n)
        M = Xs[argmin(errors)]
        if minimum(errors) == 0 
            return M
        end
    end
    return M
end

go! (generic function with 1 method)

In [55]:
for i in 1:10
    X3 =
    [1 2 3
     4 5 6
     7 8 9]
    X3 = go!(X3,3)
    k = 10
    remainders = reverse(collect(k:k*k))
    X = zeros(Int32, k, k)
    for i in 1:k
        for j in 1:k
            if i <= 3 && j <= 3
                X[i,j] = X3[i,j]
            else
                X[i,j] = pop!(remainders)
            end
        end
    end
    X = mutate(X,1000,k)

    display("Start")
    display(i)
    Solution = go!(X, k)
    display(Solution)
    display(fitness(Solution,k))
    display("End")
end

"Start"

1

10×10 Matrix{Int32}:
  8    1   6  74  68  89  98  55  69  37
  3    5   7  83  90  64  77  45  46  85
  4    9   2  39  15  91  65  93  99  88
 87  100  49  57  44  17  21  26  42  62
 79   63  59  35  72  18  76  27  40  36
 94   78  75  19  25  80  31  10  70  23
 67   38  92  96  41  73  53  12  20  13
 61   43  47  56  60  29  28  95  54  32
 50   71  86  16  66  11  22  84  51  48
 52   97  82  30  24  33  34  58  14  81

2

"End"

"Start"

2

10×10 Matrix{Int32}:
  2    9   4  51  66  82  70  98  46  77
  7    5   3  95  69  96  76  65  25  64
  6    1   8  74  59  62  86  92  23  94
 68   88  97  36  13  16  75  15  84  12
 99   67  87  80  39  21  11  30  54  17
 26  100  73  47  32  85  19  38  45  40
 31   56  58  10  89  41  60  52  71  37
 83   53  48  43  42  61  29  63  34  50
 93   35  55  20  78  27  57  28  79  33
 90   91  72  49  18  14  22  24  44  81

49

"End"

"Start"

3

10×10 Matrix{Int32}:
  2   9   4  81   98  86  71  73  56  25
  7   5   3  99   58  36  75  62  79  82
  6   1   8  43  100  39  96  67  64  80
 66  55  20  77   10  60  28  61  87  41
 94  95  97  12   84  37  11  18  40  17
 24  83  92  33   14  93  13  50  46  57
 88  51  85  29   21  31  76  42  35  47
 65  89  72  30   45  69  53  48  15  19
 90  91  70  27   52  22  44  16  34  59
 63  26  54  74   23  32  38  68  49  78

2

"End"

"Start"

4

10×10 Matrix{Int32}:
   4   9   2  73  90  67  40  95  83  42
   3   5   7  87  38  97  85  51  54  78
   8   1   6  88  93  35  76  94  49  55
  32  71  79  68  53  11  29  60  21  81
  89  44  77  13  70  57  20  33  74  28
  84  98  92  46  43  26  31  19  52  14
  99  59  91  27  17  66  30  24  45  47
 100  64  37  56  41  16  62  96  23  10
  36  72  34  25  48  69  75  18  65  63
  50  82  80  22  12  61  58  15  39  86

51

"End"

"Start"

5

10×10 Matrix{Int32}:
  2    9   4  68  70  98  74  47  97  36
  7    5   3  57  90  65  72  88  39  79
  6    1   8  99  16  82  84  31  86  92
 95  100  61  38  40  10  34  81  13  33
 66   25  63  32  89  73  37  42  35  43
 20   87  77  56  55  54  51  27  52  26
 67   64  76  62  28  46  58  45  48  12
 69   94  71  18  53  17  29  91  41  21
 93   24  83  15  14  49  44  30  75  78
 80   96  59  60  50  11  22  23  19  85

2

"End"

"Start"

6

10×10 Matrix{Int32}:
  2   9    4  95  50  88  70  80  65  42
  7   5    3  35  77  76  97  78  31  96
  6   1    8  57  84  20  64  75  91  99
 85  79   51  81  92  15  40  17  32  13
 98  66   67  53  60  12  23  24  30  72
 39  90   82  48  29  87  44  61  14  10
 59  62   45  38  19  63  36  74  55  54
 71  94   93  18  27  34  26  58  73  11
 49  56   52  33  46  69  68  22  86  25
 89  43  100  47  21  41  37  16  28  83

3

"End"

"Start"

7

10×10 Matrix{Int32}:
  2   9    4  93  71  43  96  85  60  42
  7   5    3  68  70  94  39  80  53  86
  6   1    8  49  89  99  45  84  69  55
 33  13  100  66  63  40  35  27  41  87
 97  81   73  22  72  67  38  26  19  10
 95  98   47  32  30  48  28  36  37  54
 79  82   83  11  52  16  90  24  56  12
 46  64   34  92  20  25  88  61  57  18
 65  74   77  58  21  44  31  23  62  50
 75  78   76  14  17  29  15  59  51  91

0

"End"

"Start"

8

10×10 Matrix{Int32}:
   2   9   4  74  78  52  72  70  83  61
   7   5   3  85  84  56  46  88  54  76
   6   1   8  43  39  86  41  92  90  99
 100  63  91  55  17  20  51  42  53  13
  64  57  93  11  94  25  49  18  79  15
  34  95  59  44  23  97  29  77  12  35
  96  98  73  68  16  22  28  47  10  48
  89  75  67  33  50  21  62  38  30  40
  81  37  36  60  24  69  82  19  66  31
  27  65  71  32  80  58  45  14  26  87

31

"End"

"Start"

9

10×10 Matrix{Int32}:
  8   1   6   82  83  56  77  61  58  73
  3   5   7   85  45  38  65  90  68  99
  4   9   2   74  93  51  72  54  89  57
 39  88  98  100  34  37  10  21  16  62
 76  94  20   11  78  47  64  42  43  30
 86  75  24   22  26  84  41  19  59  69
 17  71  80   14  44  40  55  87  48  49
 96  70  91   66  27  12  53  46  31  13
 79  25  81   28  60  50  32  52  63  35
 97  67  95   23  15  92  36  33  29  18

50

"End"

"Start"

10

10×10 Matrix{Int32}:
  8   3   4  60  59  61  49  79  82  100
  1   5   9  38  46  77  80  57  93   99
  6   7   2  56  43  94  90  47  74   86
 83  39  91  96  41  16  18  45  51   25
 66  95  53  12  89  30  14  78  58   10
 75  73  65  22  36  76  29  20  37   72
 62  88  63  32  50  69  70  31  19   21
 68  97  85  26  33  17  67  84  15   13
 81  11  98  71  44  42  34  24  48   52
 55  87  35  92  64  23  54  40  28   27

2

"End"